package net.filmix.client

import net.filmix.core.model.Post

/**
 * Phase-1 placeholder content, captured verbatim from a live
 * `GET /api/v2/catalog` response so the layout is exercised with real
 * titles, posters and quality labels. Replaced by the repository in phase 3.
 */
object MockData {

    val featured = Post(
        id = 186499,
        title = "Бэтмен: Падение рыцаря. Часть первая",
        originalTitle = "Batman: Knightfall, Part 1",
        year = 2026,
        posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/betmen-padenie-rycarya-chast-pervaya-2026_186499_0.jpg",
        quality = "WEB-DLRip 2160",
        countries = listOf("США"),
        categories = listOf("Приключения", "Триллеры", "Боевики"),
        shortStory = "Когда загадочный гигант по имени Бэйн совершает дерзкий побег и выпускает из лечебницы Аркхем самых опасных врагов Бэтмена, Готэм погружается в хаос.",
    )

    val newest: List<Post> = listOf(
        Post(
            id = 186520,
            section = 0,
            title = "Опасное место",
            originalTitle = "Hot Spot",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/opasnoe-mesto-2026_186520_0.jpg",
            quality = "TC 1080",
            countries = listOf("Греция", "Норвегия", "Польша"),
            categories = listOf("Драмы", "Триллеры", "Криминал"),
        ),
        Post(
            id = 8975,
            section = 93,
            title = "Футурама",
            originalTitle = "Futurama",
            year = 1999,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/novi-4w-futurama-2010_8975_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("США"),
            categories = listOf("Для взрослых", "Фантастика", "Приключения"),
        ),
        Post(
            id = 186521,
            section = 7,
            title = "Большая фарма",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/bolshaya-farma-2026_186521_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Драмы", "Сериалы"),
        ),
        Post(
            id = 186373,
            section = 7,
            title = "Малой",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/maloy-2026_186373_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Россия"),
            categories = listOf("Комедия", "Сериалы"),
        ),
        Post(
            id = 186500,
            section = 7,
            title = "Остатки золота",
            originalTitle = "Remnants of Gold",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/ostatki-zolota-2026_186500_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Китай"),
            categories = listOf("Драмы", "Детектив", "Сериалы"),
        ),
        Post(
            id = 8294,
            section = 7,
            title = "Безумцы",
            originalTitle = "Mad Men",
            year = 2007,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/20ll22-bezumcy-2010_8294_0.jpg",
            quality = "WEB-DLRip 720",
            countries = listOf("США"),
            categories = listOf("Сериалы", "Драмы", "На украинском"),
        ),
        Post(
            id = 185804,
            section = 7,
            title = "Холод",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/holod-2026_185804_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Драмы", "Криминал", "Сериалы"),
        ),
        Post(
            id = 185927,
            section = 0,
            title = "Мотор Сити",
            originalTitle = "Motor City",
            year = 2025,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/motor-siti-2025_185927_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("США"),
            categories = listOf("Драмы", "Триллеры", "Криминал"),
        ),
    )

    val popular: List<Post> = listOf(
        Post(
            id = 186476,
            section = 7,
            title = "Гудовы",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/gudovy-2026_186476_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Комедия", "Сериалы"),
        ),
        Post(
            id = 186067,
            section = 0,
            title = "Человек-паук: Новый день",
            originalTitle = "Spider-Man: Brand New Day",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/chelovek-pauk-novyy-den-2026_186067_0.jpg",
            quality = "WEBRip 1080",
            countries = listOf("США"),
            categories = listOf("Фантастика", "Фэнтези", "Приключения"),
        ),
        Post(
            id = 186439,
            section = 7,
            title = "Дэнг и его гангстеры",
            originalTitle = "Dang and His Gangsters",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/deng-i-ego-gangstery-2026_186439_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Таиланд"),
            categories = listOf("Драмы", "Боевики", "Сериалы"),
        ),
        Post(
            id = 186014,
            section = 93,
            title = "Президент Кертис",
            originalTitle = "President Curtis",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/prezident-kertis-2026_186014_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("США"),
            categories = listOf("Фантастика", "Комедия", "Мультсериалы"),
        ),
        Post(
            id = 185834,
            section = 7,
            title = "Один на один: Австралия",
            originalTitle = "Alone Australia",
            year = 2023,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/odin-na-odin-avstraliya-2023_185834_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Австралия"),
            categories = listOf("Реальное ТВ", "Сериалы", "Игра"),
        ),
        Post(
            id = 166670,
            section = 7,
            title = "Обычный Джо",
            originalTitle = "Average Joe",
            year = 2023,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/obychnyy-dzho-2023_166670_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("США"),
            categories = listOf("Драмы", "Комедия", "Сериалы"),
        ),
        Post(
            id = 186510,
            section = 7,
            title = "Май нейм из Гутьеррес",
            originalTitle = "Guti&#233;rrez is mai neim",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/may-neym-iz-guterres-2026_186510_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Аргентина"),
            categories = listOf("Криминал", "Боевики", "Комедия"),
        ),
        Post(
            id = 186457,
            section = 0,
            title = "Тайна Нетландии",
            originalTitle = "Before Never",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/tayna-netlandii-2026_186457_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("США"),
            categories = listOf("Драмы", "Триллеры"),
        ),
    )

    val series: List<Post> = listOf(
        Post(
            id = 8975,
            section = 93,
            title = "Футурама",
            originalTitle = "Futurama",
            year = 1999,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/novi-4w-futurama-2010_8975_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("США"),
            categories = listOf("Для взрослых", "Фантастика", "Приключения"),
        ),
        Post(
            id = 186521,
            section = 7,
            title = "Большая фарма",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/bolshaya-farma-2026_186521_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Драмы", "Сериалы"),
        ),
        Post(
            id = 186373,
            section = 7,
            title = "Малой",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/maloy-2026_186373_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Россия"),
            categories = listOf("Комедия", "Сериалы"),
        ),
        Post(
            id = 186500,
            section = 7,
            title = "Остатки золота",
            originalTitle = "Remnants of Gold",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/ostatki-zolota-2026_186500_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Китай"),
            categories = listOf("Драмы", "Детектив", "Сериалы"),
        ),
        Post(
            id = 8294,
            section = 7,
            title = "Безумцы",
            originalTitle = "Mad Men",
            year = 2007,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/20ll22-bezumcy-2010_8294_0.jpg",
            quality = "WEB-DLRip 720",
            countries = listOf("США"),
            categories = listOf("Сериалы", "Драмы", "На украинском"),
        ),
        Post(
            id = 185804,
            section = 7,
            title = "Холод",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/holod-2026_185804_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Драмы", "Криминал", "Сериалы"),
        ),
        Post(
            id = 186476,
            section = 7,
            title = "Гудовы",
            originalTitle = "",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/gudovy-2026_186476_0.jpg",
            quality = "WEB-DLRip 2160",
            countries = listOf("Россия"),
            categories = listOf("Комедия", "Сериалы"),
        ),
        Post(
            id = 186439,
            section = 7,
            title = "Дэнг и его гангстеры",
            originalTitle = "Dang and His Gangsters",
            year = 2026,
            posterUrl = "http://thumbs.filmixapp.cyou/posters/1221/thumbs/w220/deng-i-ego-gangstery-2026_186439_0.jpg",
            quality = "WEB-DLRip 1080",
            countries = listOf("Таиланд"),
            categories = listOf("Драмы", "Боевики", "Сериалы"),
        ),
    )

}
